version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - mynetwork
    depends_on:
      - coordenador
    deploy:
      replicas: 3

  coordenador:
    build: 
      context: ./coordenador
      dockerfile: Dockerfile
      
    networks:
      - mynetwork
    
  shard_a: 
    build:
      context: ./shard_a
      dockerfile: Dockerfile
    networks:
      - mynetwork
    depends_on:
      - coordenador
    
  shard_b:
    build:
      context: ./shard_b
      dockerfile: Dockerfile
    networks:
      - mynetwork
    depends_on:
      - coordenador

    
networks:
  mynetwork: