version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - mynetwork
    depends_on:
      - coordenador
    volumes:
      - ./client:/client
    deploy:
      replicas: 3

  coordenador:
    build: 
      context: ./coordenador
      dockerfile: Dockerfile
    
    volumes:
      - ./coordenador:/coordenador
    networks:
      - mynetwork
    
  shard_a: 
    build:
      context: ./shard_a
      dockerfile: Dockerfile
    volumes:
      - ./shard_a:/shard_a
    networks:
      - mynetwork
    depends_on:
      - coordenador
    
  shard_b:
    build:
      context: ./shard_b
      dockerfile: Dockerfile
    volumes:
      - ./shard_b:/shard_b
    networks:
      - mynetwork
    depends_on:
      - coordenador

    
networks:
  mynetwork: